[package]
name = "simplers"
version = "1.0.8"
edition = "2021"
description = "Simplification of too complex stuff in rust"
readme = "README.md"
authors = ["Coderspark"]
license = "Apache-2.0"
repository = "https://github.com/coderspark/simplers"
exclude = [
    ".gitignore"
]

[dependencies]
